- become: true
  hosts: all
  name: Configure hosts
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: hosts

- become: true
  hosts: hypervisors
  name: Configure hypervisors
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: hypervisors