---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 1h
  values:
    preferIpv6: true
    ipv6:
      enabled: true
    rollOutCiliumPods: true
    routingMode: native
    ipv4NativeRoutingCIDR: 10.30.0.0/16
    ipv6NativeRoutingCIDR: fd00:10:30::/56
    enableIPv6BIGTCP: true
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    enableIPv4BIGTCP: true
    bpfClockProbe: true
    bgpControlPlane:
      enabled: true
    bandwidthManager:
      enabled: true
      bbr: true
    socketLB:
      enabled: true
    endpointRoutes:
      enabled: true
    envoy:
      enabled: false
    pmtuDiscovery:
      enabled: true
    ipam:
      mode: kubernetes
    bpf:
      datapathMode: netkit
      masquerade: true
      preallocateMaps: true
      distributedLRU:
        enabled: true
      mapDynamicSizeRatio: 0.08
    loadBalancer:
      acceleration: best-effort
      algorithm: maglev
      mode: dsr
    l7Proxy: false
    gatewayAPI:
      enabled: false
    hubble:
      relay:
        enabled: true
        replicas: 2
        rollOutPods: true
      ui:
        enabled: true
        replicas: 2
        rollOutPods: true
    operator:
      replicas: 2
      rollOutPods: true
    securityContext:
      capabilities:
        ciliumAgent:
          [
            CHOWN,
            KILL,
            NET_ADMIN,
            NET_RAW,
            IPC_LOCK,
            SYS_ADMIN,
            SYS_RESOURCE,
            DAC_OVERRIDE,
            FOWNER,
            SETGID,
            SETUID,
          ]
        cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    dashboards:
      enabled: true
