---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security-system
spec:
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 1h
  values:
    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret-key
              key: password
        - name: AUTHENTIK_POSTGRESQL__SSLMODE
          value: verify-full
        - name: AUTHENTIK_POSTGRESQL__SSLCERT
          value: /var/run/secrets/postgresql/tls.crt
        - name: AUTHENTIK_POSTGRESQL__SSLKEY
          value: /var/run/secrets/postgresql/tls.key
        - name: AUTHENTIK_POSTGRESQL__SSLROOTCERT
          value: /var/run/secrets/postgresql/ca.crt
    authentik:
      postgresql:
        host: postgres-rw.storage-system
        name: authentik
        user: authentik
    server:
      replicas: 2
      extraVolumes:
        - name: pg-client-cert
          secret:
            secretName: authentik
      extraVolumeMounts:
        - name: pg-client-cert
          mountPath: /var/run/secrets/postgresql
          readOnly: true
      route:
        main:
          enabled: true
          parentRefs:
            - name: envoy
              namespace: network-system
          hostnames:
            - authentik.paradisenetworkz.com
    worker:
      replicas: 2
      extraVolumes:
        - name: pg-client-cert
          secret:
            secretName: authentik
      extraVolumeMounts:
        - name: pg-client-cert
          mountPath: /var/run/secrets/postgresql
          readOnly: true
