---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-system

components:
  - ../../../components/postgres/

configMapGenerator:
  - name: postgres-app-params
    options:
      disableNameSuffixHash: true
    literals:
      - APP=authentik

resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
