---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-system

components:
  - ../../../components/postgres/

configMapGenerator:
  - name: postgres-app-params
    options:
      disableNameSuffixHash: true
    literals:
      - APP=authentik-idp
      - PGURL=postgresql://authentik-idp@postgres-rw.storage-system:5432/authentik-idp?sslmode=verify-full&sslcert=/var/run/secrets/postgresql/tls.crt&sslkey=/var/run/secrets/postgresql/tls.key&sslrootcert=/var/run/secrets/postgresql/ca.crt

resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
