---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 15m
  ref:
    tag: 1.20.1
  url: oci://registry.k8s.io/sig-storage/csi-driver-smb
