- name: Restart frr
  ansible.builtin.service: 
    name: frr
    state: restarted

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: restarted

- name: Restart zerotier
  ansible.builtin.service:
    name: zerotier-one
    enabled: true
    state: restarted