---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-replica-1
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  property.linstor.csi.linbit.com/DrbdOptions/Net/tls: "yes"
  linstor.csi.linbit.com/storagePool: vg1-thin
  linstor.csi.linbit.com/placementCount: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-replica-2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  property.linstor.csi.linbit.com/DrbdOptions/Net/tls: "yes"
  linstor.csi.linbit.com/storagePool: vg1-thin
  linstor.csi.linbit.com/placementCount: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-replica-3
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  property.linstor.csi.linbit.com/DrbdOptions/Net/tls: "yes"
  linstor.csi.linbit.com/storagePool: vg1-thin
  linstor.csi.linbit.com/placementCount: "3"