apiVersion: v1
kind: Namespace 
metadata: 
  name: netbox
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: postgres-creds
  data:
    - secretKey: postgres-password
      remoteRef:
        key: POSTGRES_ADMIN_PASS
    - secretKey: password
      remoteRef:
        key: POSTGRES_PASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: redis-creds
  data:
    - secretKey: password
      remoteRef:
        key: REDIS_PASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-creds
  namespace: netbox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: netbox-creds
  data:
    - secretKey: secret_key
      remoteRef:
        key: NETBOX_SECRET_KEY
    - secretKey: superuser_password
      remoteRef:
        key: SUPERUSER_PASSWORD
    - secretKey: superuser_api_token
      remoteRef:
        key: SUPERUSER_API_TOKEN