- become: true
  hosts: all
  name: Hardening control-plane
  vars_files:
    - vars/cis.yaml
  tasks:
    - name: Hardening route controllers
      ansible.builtin.include_role:
        name: UBUNTU22-CIS
      vars:
        ubtu22cis_dns_server: true
      when: inventory_hostname in groups['route_controllers']
    
    - name: Hardening k8s hosts
      ansible.builtin.include_role:
        name: UBUNTU22-CIS
      when: inventory_hostname in (groups['k8s_server'] or groups['k8s_agent'])