- become: true
  hosts: all
  name: Hardening control-plane
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Include all vars
      ansible.builtin.include_vars:
        dir: vars

    - name: Hardening route controllers
      ansible.builtin.include_role:
        name: UBUNTU22-CIS
      vars:
        ubtu22cis_dns_server: true
      when: inventory_hostname in groups['route_controllers']
    
    - name: Hardening ingresses
      ansible.builtin.include_role:
        name: UBUNTU22-CIS
      when: inventory_hostname in groups['ingresses']