- become: true
  hosts: all
  name: Configure control plane
  tasks:
    - name: Configure route controllers
      ansible.builtin.include_role: 
        name: route-controller
      when: inventory_hostname in groups['route_controllers']

    - name: Configure ingresses
      ansible.builtin.include_role: 
        name: ingress
      when: inventory_hostname in groups['ingresses']