- become: true
  hosts: all
  name: Configure control-plane
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Include all vars
      ansible.builtin.include_vars:
        dir: vars

    - name: Configure hosts
      ansible.builtin.include_role: 
        name: hosts

    - name: Configure route controllers
      ansible.builtin.include_role: 
        name: route-controllers
      when: inventory_hostname in groups['route_controllers']

    - name: Configure ingresses
      ansible.builtin.include_role: 
        name: ingresses
      when: inventory_hostname in groups['ingresses']