- become: true
  hosts: all
  name: Configure control-plane
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/control-plane.yaml"
  vars_files:
    - vars/control-plane.yaml
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Configure route controllers
      ansible.builtin.include_role: 
        name: route-controllers
      when: inventory_hostname in groups['route_controllers']

    - name: Configure k8s hosts
      ansible.builtin.include_role: 
        name: k8s
      when: inventory_hostname in (groups['k8s_server'] or groups['k8s_agent'])