- become: true
  hosts: all
  name: Configure control-plane
  vars_files:
    - vars/control-plane.yaml
  tasks:
    - name: Configure route controllers
      ansible.builtin.include_role: 
        name: route-controllers
      when: inventory_hostname in groups['route_controllers']

    - name: Configure k8s hosts
      ansible.builtin.include_role: 
        name: k8s
      when: inventory_hostname in (groups['k8s_server'] or groups['k8s_agent'])