---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secret-store
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com.
      identityURL: https://identity.bitwarden.com.
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-ca-certs
        key: ca.crt
        namespace: external-secrets
      organizationID: fe3d4e33-20e4-45f7-aec5-b48c014121e3
      projectID: 9755e1d4-89f4-4dc2-838f-b48c01414989
