---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  path: kubernetes/cluster-apps/external-secrets/app
  prune: true
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: spegel
      namespace: spegel
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m