---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: network-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
  target:
    name: mikrotik-credentials
  data:
    - secretKey: MIKROTIK_BASEURL
      remoteRef:
        key: MIKROTIK_BASEURL
    - secretKey: MIKROTIK_USERNAME
      remoteRef:
        key: MIKROTIK_USERNAME
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        key: MIKROTIK_PASSWORD
    - secretKey: MIKROTIK_SKIP_TLS_VERIFY
      remoteRef:
        key: MIKROTIK_SKIP_TLS_VERIFY
