---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-main-pgbackrest-smb
  namespace: database-system
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: pg-main-pgbackrest-smb
    volumeAttributes:
      source: "//truenas.paradisenetworkz.com/percona-postgres-backups"
      subDir: "pg-main"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kube-system
  mountOptions:
    - vers=3.0
    - seal
    - noserverino
    - mfsymlinks
    - cache=strict
    - noperm
    - dir_mode=0755
    - file_mode=0644
