---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability-system
  labels:
    dashboards: grafana
spec:
  disableDefaultAdminSecret: true
  disableDefaultSecurityContext: All
  deployment:
    spec:
      strategy:
        type: Recreate
      replicas: 2
      template:
        spec:
          volumes:
            - name: pg-client-cert
              csi:
                driver: csi.cert-manager.io
                readOnly: true
                volumeAttributes:
                  csi.cert-manager.io/issuer-name: root-ca-clusterissuer
                  csi.cert-manager.io/issuer-kind: ClusterIssuer
                  csi.cert-manager.io/common-name: grafana
                  csi.cert-manager.io/key-usages: client auth
                  csi.cert-manager.io/fs-group: "1000"
          containers:
            - name: grafana
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
              volumeMounts:
                - name: pg-client-cert
                  mountPath: /var/run/secrets/postgresql
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
  config:
    log:
      mode: "console"
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "True"
    database:
      type: "postgres"
      host: "postgres-rw.storage-system:5432"
      name: "grafana"
      user: "grafana"
      ssl_mode: "verify-full"
      ca_cert_path: "/var/run/secrets/postgresql/ca.crt"
      client_cert_path: "/var/run/secrets/postgresql/tls.crt"
      client_key_path: "/var/run/secrets/postgresql/tls.key"
    unified_alerting:
      enabled: "true"
      ha_listen_address: "${POD_IP}:9094"
      ha_peers: "grafana-alerting:9094"
      ha_advertise_address: "${POD_IP}:9094"
      ha_peer_timeout: 15s
      ha_reconnect_timeout: 2m
    metrics:
      enabled: "true"
    server:
      enable_gzip: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
  httpRoute:
    spec:
      parentRefs:
        - name: envoy
          namespace: network-system
      hostnames:
        - grafana.home.paradisenetworkz.com
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: grafana-service
              port: 3000
