default_provider = "bws"

[providers.age]
type = "age"
recipients = ["age1vgn6yadgyqafhjs34t4qh6p9ugulreuemqg2582lqavt94dea35qcukugc"]

[providers.keychain]
type = "keychain"
service = "fnox"

[providers.bws]
type = "bitwarden-sm"
project_id = "177380c1-6ec7-4b0e-a080-b46a0012d805"

[secrets]
BWS_ACCESS_TOKEN = { provider = "keychain", value = "BWS_ACCESS_TOKEN" }
TALOS_CLUSTER_ID = { provider = "bws", value = "TALOS_CLUSTER_ID" }
TALOS_CLUSTER_SECRET = { provider = "bws", value = "TALOS_CLUSTER_SECRET" }
TALOS_SECRETS_BOOTSTRAPTOKEN = { provider = "bws", value = "TALOS_SECRETS_BOOTSTRAPTOKEN" }
TALOS_SECRETS_SECRETBOXENCRYPTIONSECRET = { provider = "bws", value = "TALOS_SECRETS_SECRETBOXENCRYPTIONSECRET" }
TALOS_TRUSTDINFO_TOKEN = { provider = "bws", value = "TALOS_TRUSTDINFO_TOKEN" }
TALOS_CERTS_ETCD_CRT = { provider = "bws", value = "TALOS_CERTS_ETCD_CRT" }
TALOS_CERTS_ETCD_KEY = { provider = "bws", value = "TALOS_CERTS_ETCD_KEY" }
TALOS_CERTS_K8S_CRT = { provider = "bws", value = "TALOS_CERTS_K8S_CRT" }
TALOS_CERTS_K8S_KEY = { provider = "bws", value = "TALOS_CERTS_K8S_KEY" }
TALOS_CERTS_K8SAGGREGATOR_CRT = { provider = "bws", value = "TALOS_CERTS_K8SAGGREGATOR_CRT" }
TALOS_CERTS_K8SAGGREGATOR_KEY = { provider = "bws", value = "TALOS_CERTS_K8SAGGREGATOR_KEY" }
TALOS_CERTS_K8SSERVICEACCOUNT_KEY = { provider = "bws", value = "TALOS_CERTS_K8SSERVICEACCOUNT_KEY" }
TALOS_CERTS_OS_CRT = { provider = "bws", value = "TALOS_CERTS_OS_CRT" }
TALOS_CERTS_OS_KEY = { provider = "bws", value = "TALOS_CERTS_OS_KEY" }
