image: ubuntu

cache:
  key: "$CI_PROJECT_NAME"

default:
  before_script:
    - apt update && apt install -y curl gnupg unzip
    - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
    - curl -o terraform_1.5.2_linux_amd64.zip https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip
    - unzip terraform_1.5.2_linux_amd64.zip
    - chmod +x terraform
    - echo "$DOPPLER_TOKEN" | doppler configure set token --scope $CI_PROJECT_DIR
    - doppler run -- ./terraform init
stages:
  - validate
  - plan
  - apply
  - destroy

validate-job:
  stage: validate
  script:    
    - doppler run -- ./terraform validate

plan-job:
  stage: plan
  script:
    - doppler run -- ./terraform plan

apply-job:
  stage: apply
  script:
    - apt install python3
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - python3 -m pip install ansible"
    - doppler run -- ./terraform apply -auto-approve
    - doppler run -- ansible-playbook -i ./ansible/inventory -u deploy ./ansible/local.yml

destroy-job:
  stage: destroy
  script:
    - doppler run -- ./terraform destroy -auto-approve
  when: manual