[env]
KUBECONFIG  = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"

[shell_alias]
k = "kubectl"
t = "talosctl"

[tools]
fnox                           = "1.34.1"
just                           = "1.51.0"
kubectl                        = "1.36.1"
talosctl                       = "1.14.0-rc.2"
uv                             = "latest"
vals                           = "0.44.0"
yq                             = "4.53.3"
"aqua:postfinance/topf"        = "0.5.0"
"github:home-operations/flate" = "0.3.2"
"pipx:oci-cli"                 = "3.90.3"
