[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"

[shell_alias]
k = "kubectl"
t = "talosctl"

[tools]
"aqua:postfinance/topf" = "0.4.1"
doppler = "3.76.0"
"github:home-operations/flate" = "0.3.2"
just = "1.51.0"
kubectl = "1.36.1"
talosctl = "1.13.3"
vals = "0.44.0"
yq = "4.53.3"
