---
- name: Apply Helm Charts & Manifests
  become: false
  hosts: localhost
  vars_files:
    - talos/cluster.yaml
  tasks:
    - name: Apply-Manifests | Apply helm charts
      kubernetes.core.helm:
        name: "{{ item.name }}"
        chart_ref: "{{ item.chart_ref }}"
        chart_version: "{{ item.chart_version }}"
        release_namespace: "{{ item.release_namespace }}"
        create_namespace: true
        values: "{{ item['values'] }}"
      loop: "{{ charts }}"

    - name: Apply-Manifests | Apply flux seed repo
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'talos/flux-seed-repo.yaml') | from_yaml }}"
        wait: true
