- become: true
  hosts: all
  name: CIS-Hardening
  vars_files:
    - vars/cis-hardening-default.yaml
  pre_tasks:
    - name: Wait For Hosts To Be Availiable
      ansible.builtin.wait_for:
        timeout: 300
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
      connection: local
      become: false
  roles:
    - role: UBUNTU22-CIS