- name: Cluster Bootstrap
  hosts: localhost
  vars:
    bootstrap_talos_version: 1.12.6
  tasks:
    - name: Retrieve sops credentials
      ansible.builtin.set_fact:
        sops_age_key: "{{ lookup('community.general.bitwarden', 'sops-age-talos', field = 'private-key') | first }}"
        sops_age_recipients: "{{ lookup('community.general.bitwarden', 'sops-age-talos', field = 'public-key') | first }}"

    - name: Retrieve schematic id
      ansible.builtin.uri:
        url: https://factory.talos.dev/schematics
        method: POST
        body: "{{ lookup('ansible.builtin.file', 'talos/schematic.yaml') }}"
        body_format: raw
        status_code: 201
      register: bootstrap_schematic

    - name: Ensure correct machine image config
      ansible.builtin.copy:
        content: |
          machine:
            install:
              image: factory.talos.dev/metal-installer-secureboot/{{ bootstrap_schematic.json.id }}:v{{ bootstrap_talos_version }}
        dest: talos/all/02-image.yaml
        mode: '0644'

    - name: Ensure talosconfig exists
      ansible.builtin.shell: "topf talosconfig > {{ playbook_dir }}/talosconfig"
      args:
        chdir: talos
        creates: "{{ playbook_dir }}/talosconfig"
      environment:
        SOPS_AGE_KEY: "{{ sops_age_key }}"
        SOPS_AGE_RECIPIENTS: "{{ sops_age_recipients }}"

    - name: Ensure talos machine configs are applied
      ansible.builtin.command: topf apply --confirm=false --auto-bootstrap=true --allow-not-ready=true
      args:
        chdir: talos
      register: bootstrap_apply_config
      changed_when:
        - bootstrap_apply_config.stderr | regex_search("applied machine config") is not none
      environment:
        SOPS_AGE_KEY: "{{ sops_age_key }}"
        SOPS_AGE_RECIPIENTS: "{{ sops_age_recipients }}"

    - name: Ensure kubeconfig exists
      ansible.builtin.shell: "topf kubeconfig --validity=8760h > {{ playbook_dir }}/kubeconfig"
      args:
        chdir: talos
        creates: "{{ playbook_dir }}/kubeconfig"
      environment:
        SOPS_AGE_KEY: "{{ sops_age_key }}"
        SOPS_AGE_RECIPIENTS: "{{ sops_age_recipients }}"
