apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-linux-controlplane
  labels:
    app: talos-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80