---
- name: Stop pxe services
  delegate_to: localhost
  run_once: true
  community.docker.docker_compose_v2:
    project_name: pxe
    wait: true
    state: absent
    definition:
      services:
        matchbox:
          image: quay.io/poseidon/matchbox:v{{ matchbox_image_version }}
          environment:
            - TZ=America/New_York
            - MATCHBOX_ADDRESS={{ ansible_controller_ip }}:8080
            - MATCHBOX_LOG_LEVEL=debug
          network_mode: host
          volumes:
            - "{{ playbook_dir }}/files/{{ cluster_name }}/matchbox:/var/lib/matchbox"
          restart: always

        dnsmasq:
          image: quay.io/poseidon/dnsmasq:v{{ poseidon_dnsmasq_image_version }}
          network_mode: host
          cap_add:
            - NET_ADMIN
          restart: always
          command: '-d -q
            --dhcp-range={{ ansible_controller_network }},proxy,{{ ansible_controller_netmask }}
            --enable-tftp
            --tftp-root=/var/lib/tftpboot
            --dhcp-userclass=set:ipxe,iPXE
            --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe
            --pxe-service=tag:ipxe,x86PC,"iPXE",http://{{ ansible_controller_ip }}:8080/boot.ipxe
            --pxe-service=tag:#ipxe,X86-64_EFI,"PXE chainload to iPXE UEFI",ipxe.efi
            --pxe-service=tag:ipxe,X86-64_EFI,"iPXE UEFI",http://{{ ansible_controller_ip }}:8080/boot.ipxe
            --log-queries
            --log-dhcp'
