---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: smb-credentials
  data:
    - secretKey: username
      remoteRef:
        key: smb-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: smb-credentials
        property: password
