- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow neccessary ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: '179'
      proto: tcp
    - port: '2379:2381'
      proto: tcp
    - port: '4240'
      proto: tcp
    - port: '4244:4245'
      proto: tcp
    - port: '4250:4251'
      proto: tcp
    - port: '6060:6062'
      proto: tcp
    - port: '9878:9879'
      proto: tcp
    - port: '9890:9891'
      proto: tcp
    - port: '9893'
      proto: tcp
    - port: '9962:9964'
      proto: tcp
    - port: '9345'
      proto: tcp
    - port: '6443'
      proto: tcp
    - port: '10250'
      proto: tcp
    - port: '30000:32767'
      proto: tcp

- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart frr

- name: write the frr config file
  ansible.builtin.template: 
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived
  when: inventory_hostname in groups['k8s_server']