- name: Add zerotier pgp key
  ansible.builtin.apt_key:
    url: https://download.zerotier.com/contact@zerotier.com.gpg
    id: 74A5E9C458E1A431F1DA57A71657198823E52A61

- name: Add zerotier apt repository
  ansible.builtin.apt_repository:
    repo: deb http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main
    filename: zerotier

- name: Add vector gpg key
  ansible.builtin.get_url:
    url: https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
    dest: /usr/share/keyrings/timber-vector-archive-keyring.asc
    mode: '0644'

- name: Add vector apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/timber-vector-archive-keyring.asc] https://repositories.timber.io/public/vector/deb/ubuntu {{ ansible_facts['distribution_release'] }} main

- name: Installing needed applications
  ansible.builtin.apt:
    name:
      - zerotier-one
      - frr
      - vector
    state: present
    update_cache: true
  notify: Restart zerotier

- name: Installing keepalived
  ansible.builtin.apt:
    name:
      - keepalived
    state: present
    update_cache: true
  when: inventory_hostname in groups['k8s_server']

- name: Update gather facts
  ansible.builtin.setup: