---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
  match: mac(link.permanent_addr) == "6c:4b:90:55:3e:7d"
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth1
selector:
  match: mac(link.permanent_addr) == "b4:96:91:73:53:78"
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - eth0
  - eth1
bondMode: active-backup
addresses:
  - address: 10.20.0.30/24
routes:
  - gateway: 10.20.0.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.20.0.200
link: bond0
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-control-2.home.paradisenetworkz.com
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-data-1
provisioning:
  diskSelector:
    match: disk.wwid == "nvme.1987-3230313032323531323032333233-5043496520535344-00000001"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        checkSecurebootStatusOnEnroll: true
      lockToState: true
