---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network-system
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    replicaCount: 2
    domain: k8s.home.paradisenetworkz.com
    ttl: 1
    watchedResources: ["HTTPRoute"]
    service:
      type: LoadBalancer
      port: 53
      annotations:
        "lbipam.cilium.io/ips": "fd00:10:22::1"
      externalTrafficPolicy: Cluster
