---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://truenas.paradisenetworkz.com:7000
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://truenas.paradisenetworkz.com:7001
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: gcr.io
endpoints:
  - url: https://truenas.paradisenetworkz.com:7002
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://truenas.paradisenetworkz.com:7003
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: https://truenas.paradisenetworkz.com:7004
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: factory.talos.dev
endpoints:
  - url: https://truenas.paradisenetworkz.com:7005
