---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 1h
  path: kubernetes/cluster-apps/node-feature-discovery/app
  prune: true
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: spegel
      namespace: spegel
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
