apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-sm
  namespace: security-system
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: access-token
            name: bitwarden-access-token
      bitwardenServerSDKURL: https://bitwarden-sdk-server.default.svc.cluster.local:9998
      organizationID: b2b7c855-9ae1-4748-9692-b46a000f998b
      projectID: 177380c1-6ec7-4b0e-a080-b46a0012d805
