apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-sm
  namespace: security-system
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: access-token
            name: bitwarden-access-token
