---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-datastore
  namespace: piraeus-datastore
spec:
  interval: 1h
  path: kubernetes/cluster-apps/piraeus-datastore
  prune: true
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: spegel
      namespace: spegel
    - name: cert-manager
      namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m