- name: Installing Required Applications
  block:
    - name: Adding Zerotier GPG Keys
      ansible.builtin.get_url:
        url: https://download.zerotier.com/contact@zerotier.com.gpg
        dest: /etc/apt/keyrings/zerotier.com.asc
        mode: '0644'

    - name: Adding Zerotier APT Repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/zerotier.com.asc] http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main
        state: present
        update_cache: yes

    - name: Installing Applications
      ansible.builtin.apt:
        name:
          - cryptsetup
          - zerotier-one
          - frr
          - python3-pip
        state: present
        update_cache: true

    - name: Install Kubernetes Python Client
      ansible.builtin.pip:
        name: kubernetes

- name: Gathering New Facts
  ansible.builtin.setup:

- name: Configure Sysctl Values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - name: vm.panic_on_oom
      value: '0'
    - name: vm.overcommit_memory
      value: '1'
    - name: kernel.panic
      value: '10'
    - name: kernel.panic_on_oops
      value: '1'
    - name: net.ipv4.ip_forward
      value: '1'

- name: Writing Config Files
  block:
    - ansible.builtin.copy: 
        src: zerotier-conf.json
        dest: /var/lib/zerotier-one/local.conf

    - ansible.builtin.copy: 
        src: daemons
        dest: /etc/frr/daemons

    - ansible.builtin.template: 
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
      
    - name: Create RKE2 Folder Directory
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        mode: 0644

    - name: Downloading RKE2 Binary
      ansible.builtin.get_url:
        url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-{{ architecture }}
        checksum: sha256:https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/sha256sum-{{ architecture }}.txt
        dest: /usr/local/bin/rke2
        mode: 0755
  notify: 
    - Restart Zerotier
    - Restart Frr

- name: Allow Traffic
  block:
    - name: Opening Ports
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - port: '2379:2381'
          proto: tcp
        - port: '4240'
          proto: tcp
        - port: '4244:4245'
          proto: tcp
        - port: '4250:4251'
          proto: tcp
        - port: '6060:6062'
          proto: tcp
        - port: '9878:9879'
          proto: tcp
        - port: '9890:9891'
          proto: tcp
        - port: '9962:9964'
          proto: tcp
        - port: '9345'
          proto: tcp
        - port: '6443'
          proto: tcp
        - port: '10250'
          proto: tcp
        - port: '30000:32767'
          proto: tcp
        - port: '179'
          proto: tcp

    - name: Allow OSPF Multicast
      community.general.ufw:
        rule: allow
        to: "{{ item }}"
      loop: 
        - '224.0.0.5'
        - '224.0.0.6'

- name: Configure K8S Master
  block:
    - name: Creating Etcd Group
      ansible.builtin.group:
        name: etcd
        state: present

    - name: Creating Etcd User
      ansible.builtin.user:
        name: etcd
        group: etcd
        shell: /sbin/nologin
        system: true
        create_home: false
        state: present

    - name: Downloading Flux2 Tar
      ansible.builtin.get_url:
        url: https://github.com/fluxcd/flux2/releases/download/v{{ flux2_version }}/flux_{{ flux2_version }}_linux_{{ architecture }}.tar.gz
        checksum: sha256:https://github.com/fluxcd/flux2/releases/download/v{{ flux2_version }}/flux_{{ flux2_version }}_checksums.txt
        dest: /tmp/flux_{{ flux2_version }}_linux_{{ architecture }}.tar.gz
        mode: 0644

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/flux_{{ flux2_version }}_linux_{{ architecture }}.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Installing Keepalived
      ansible.builtin.apt:
        name:
          - keepalived
        state: present
        update_cache: true

    - name: Allow Keepalived Multicast
      community.general.ufw:
        rule: allow
        to: '224.0.0.18'

    - name: Creating Manifest Directory
      ansible.builtin.file:
        path: /var/lib/rancher/rke2/server/manifests
        state: directory
        mode: 0644

    - name: Creating RKE2 Master Files
      block:
        - ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: 0644
          loop:
            - src: rke2-server.service
              dest: /etc/systemd/system/rke2-server.service
            - src: audit-policy.yaml
              dest: /etc/rancher/rke2/audit-policy.yaml

        - ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: 0644
          loop:
            - src: cilium.yaml.j2
              dest: /var/lib/rancher/rke2/server/manifests/cilium.yaml
            - src: keepalived.conf.j2
              dest: /etc/keepalived/keepalived.conf
            - src: config.yaml.j2
              dest: /etc/rancher/rke2/config.yaml
      notify: 
        - Restart RKE2 Server
        - Restart Keepalived

    - name: K8S - Flushing Handlers
      meta: flush_handlers

    - name: Get Kubernetes Config File
      ansible.builtin.slurp:
        src: /etc/rancher/rke2/rke2.yaml
      register: kubeconfig_base64
      run_once: true

    - name: Writing Kubernetes Config File
      ansible.builtin.copy:
        content: "{{ kubeconfig_base64.content | b64decode | replace(hostvars[inventory_hostname]['ansible_zt0']['ipv4']['address'], (k8s_vip | ansible.utils.ipv4('address'))) }}"
        dest: "{{ kubeconfig_location }}"
        mode: 0600
      delegate_to: localhost
      run_once: true
      become: false

    - name: Creating Doppler Secret
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/rke2/rke2.yaml
        wait: true
        definition:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: external-secrets
          - apiVersion: v1
            kind: Secret
            metadata:
              name: doppler-token-auth-api
              namespace: external-secrets
            type: Opaque
            stringData:
              dopplerToken: "{{ doppler_token }}"
      run_once: true

    - name: Deploying Flux2
      ansible.builtin.command:
        argv:
          - flux
          - bootstrap
          - gitlab
          - --deploy-token-auth
          - --owner={{ gitlab_owner }}
          - --repository={{ git_repo }}
          - --branch=main
          - --path={{ git_cluster_path }}
          - --kubeconfig=/etc/rancher/rke2/rke2.yaml
          - --private=false
          - --personal
      register: result
      changed_when: result.rc != 0
      run_once: true
  when: k8s_master