---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: init
  namespace: piraeus-datastore
spec:
  interval: 1h
  path: ./piraeus-datastore/init
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m