---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-datastore
  namespace: piraeus-datastore
spec:
  interval: 1h
  path: kubernetes/apps/piraeus-datastore
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m