---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
resources:
  - https://github.com/piraeusdatastore/piraeus-operator/releases/download/v2.9.1/manifest.yaml
