---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
  properties:
    - name: DrbdOptions/Net/tls
      value: "yes"
  apiTLS:
    certManager:
      name: linstor-api-ca
      kind: Issuer
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer