---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: linstor-satellite-configuration
spec:
  storagePools:
    - name: vg1-thin
      lvmThinPool:
        volumeGroup: vg1
        thinPool: thin
      source:
        hostDevices:
          - /dev/disk/by-partlabel/r-piraeus-ssd-1
  internalTLS:
    tlsHandshakeDaemon: true
    certManager:
      name: linstor-internal-ca
      kind: Issuer