---
mac_address: 40:b0:34:f5:ac:a6
machine_config:
  machine:
    type: controlplane
    network:
      hostname: talos-control-home-1
      interfaces:
        - interface: bond0
          addresses:
            - 10.20.0.201/24
          routes:
            - network: 0.0.0.0/0
              gateway: 10.20.0.1
          bond:
            deviceSelectors:
              - permanentAddr: 40:b0:34:f5:ac:a6
            mode: active-backup
          vip:
            ip: 10.20.0.200
    install:
      disk: /dev/nvme0n1
      image: "factory.talos.dev/metal-installer/{{ schematic.json.id }}:v{{ talos_version }}"
      wipe: true