apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
  namespace: k0smotron
spec:
  version: v1.31.1+k0s.1
  etcd:
    persistence:
      storageClass: longhorn-2
      size: 8Gi
  persistence:
    type: pvc
    persistentVolumeClaim:
      spec:
        storageClassName: longhorn-2
  service:
    type: ClusterIP
    apiPort: 6443
    konnectivityPort: 8132