apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: home-cluster
  namespace: k0smotron
spec:
  version: v1.31.1+k0s.1
  etcd:
    persistence:
      storageClass: longhorn-2
      size: 8Gi
  persistence:
    type: pvc
    persistentVolumeClaim:
      spec:
        storageClassName: longhorn-2
  service:
    type: ClusterIP
    apiPort: 6443
    konnectivityPort: 8132
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
  namespace: k0smotron
spec:
  clusterNetwork:
    serviceDomain: home.paradisenetworkz.com
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: home-cluster