- name: Installing Bind9
  ansible.builtin.apt:
    name:
      - bind9
    state: present
    update_cache: true

- name: Allowing DNS
  community.general.ufw:
    rule: allow
    port: '53'

- name: Checking if tsig key exists
  ansible.builtin.stat:
    path: "/etc/bind/{{ bind_tsig_key.name }}.key"
  register: tsig_key_status
  when: bind_tsig_key is defined

- name: Creating TSIG Key
  ansible.builtin.shell: "tsig-keygen -a {{ bind_tsig_key.algorithm }} {{ bind_tsig_key.name }} > /etc/bind/{{ bind_tsig_key.name }}.key"
  register: shell_result
  changed_when: true
  when: 
    - bind_tsig_key is defined
    - not tsig_key_status.stat.exists

- name: Creating Named Configuration File
  ansible.builtin.template: 
    src: named.conf.j2
    dest: /etc/bind/named.conf
  #notify:
  #  - Restarting Bind9

#- name: Writing Config Files
#  block:
#  
#
#    - ansible.builtin.copy: 
#        src: named.conf.options
#        dest: /etc/bind/named.conf.options
#      notify:
#        - Restart Bind9
#
#    - ansible.builtin.template: 
#        src: "{{ item.src }}"
#        dest: "{{ item.dest }}"
#        group: "{{ item.group }}"
#      loop:
#        - src: forward-zone.j2
#          dest: /var/lib/bind/db.paradisenetworkz.com
#          group: bind
#        - src: reverse-zone.j2
#          dest: /var/lib/bind/db.30.10.in-addr.arpa
#          group: bind
#      notify: Restart Bind9
- name: Starting Bind9
  ansible.builtin.service: 
    name: bind9
    state: started