- name: Installing needed applications
  ansible.builtin.apt:
    name:
      - keepalived
    state: present
    update_cache: true

- name: Enable keepalived Service
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0600'
  notify: Restart keepalived

- name: Allow remote devices to access
  community.general.ufw:
    rule: allow
    route: true
    if_in: zt1
    if_out: zt0

- name: write the host frr config file
  ansible.builtin.template: 
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr

- name: Setup nginx
  include_role: 
    name: nginxinc.nginx

- name: Write the vector config file
  ansible.builtin.template: 
    src: vector.yaml.j2
    dest: /etc/vector/vector.yaml
  notify: Restart vector