- become: false
  hosts: localhost
  name: Create Hypervisor user-data
  tasks:
    - name: Create meta-data file
      ansible.builtin.copy:
        content: ""
        dest: userdata/meta-data

    - name: Create Hypervisor Home 1 user-data
      include_role: 
        name: ubuntu-autoinstall
      vars:
        hostname: hypervisor-home-1