---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.wwid == "eui.ace42e8170470927"
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
  match: mac(link.permanent_addr) == "6c:4b:90:55:3e:66"
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
up: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: eth0
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-control-3.home.paradisenetworkz.com
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-data-1
provisioning:
  diskSelector:
    match: disk.wwid == "nvme.1987-3232303431393531323030303331-5043496520535344-00000001"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
---
apiVersion: v1alpha1
kind: LVMVolumeGroupConfig
name: vg-pool
provisioning:
  volumeSelector:
    match: '"/dev/disk/by-id/dm-name-luks2-r-piraeus-data-1" in disk.symlinks'
---
apiVersion: v1alpha1
kind: BGPInstanceConfig
name: workload
vrf: vrf-workload
localASN: 4200000002
routerID: 10.20.0.66
installRoutes: false
neighbors:
  - address: "fda1:b2c3:d4e5:1::"
    peerASN: 4200000003
    passive: true
---
apiVersion: v1alpha1
kind: BGPInstanceConfig
name: fabric
localASN: 4200000001
routerID: 10.20.0.72
routeSource: fd00:10:20:0:6e4b:90ff:fe55:3e66
installRoutes: true
advertise:
  - dummy0
multipath: true
neighbors:
  - address: fd00:10:20:0:c6ad:34ff:fe8d:7f26
    peerASN: 4200000000
importRoutes:
  - bgpInstance: workload
    prefixes:
      - fd00:10:30::/56
      - fd00:10:22::/64
      - 10.30.0.0/16
