apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clastix
  namespace: flux-system
spec:
  interval: 10m
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kamaji
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: clastix
        namespace: flux-system
  values:
    kamaji-etcd:
      deploy: true
      fullnameOverride: kamaji-etcd
      datastore:
        enabled: true
        name: default
      replicas: 1
      persistentVolumeClaim:
        size: 10Gi
        storageClassName: longhorn-2