apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: default
  namespace: kamaji-system
spec:
  driver: PostgreSQL
  endpoints: ["kamaji-db-rw.kamaji-system:5432"]
  tlsConfig:
    certificateAuthority:
      certificate:
        name: kamaji-db-ca
        namespace: kamaji-system
        keyPath: ca.crt
      privateKey:
        name: kamaji-db-ca
        namespace: kamaji-system
        keyPath: ca.key
    clientCertificate:
      certificate:
        name: kamaji-client-cert
        namespace: kamaji-system
        keyPath: tls.crt
      privateKey:
        name: kamaji-client-cert
        namespace: kamaji-system
        keyPath: tls.key