apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: CLOUDFLARE_TOKEN
      remoteRef:
        key: CLOUDFLARE_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: intermediate-ca
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: intermediate-ca
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .INTERMEDIATE_CA_CRT }}"
        tls.key: "{{ .INTERMEDIATE_CA_KEY }}"
  data:
    - secretKey: INTERMEDIATE_CA_CRT
      remoteRef:
        key: INTERMEDIATE_CA_CRT
    - secretKey: INTERMEDIATE_CA_KEY
      remoteRef:
        key: INTERMEDIATE_CA_KEY
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: theo@paradisenetworkz.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: CLOUDFLARE_TOKEN
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: intermediate-ca-issuer
spec:
  ca:
    secretName: intermediate-ca