---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=helm-values.yaml
configurations:
  - kustomizeconfig.yaml