asn: "{{ lookup('ansible.builtin.env', 'ASN') }}"
aggregate_network: "{{ lookup('ansible.builtin.env', 'AGGREGATE_NETWORK') }}"
reverse_zone: "{{ lookup('ansible.builtin.env', 'REVERSE_ZONE') }}"
ingress_vip: "{{ lookup('ansible.builtin.env', 'INGRESS_VIP') }}"
tsig_key: "{{ lookup('ansible.builtin.env', 'TSIG_KEY') }}"
openobserve_user: "{{ lookup('ansible.builtin.env', 'OPENOBSERVE_USER') }}"
openobserve_pass: "{{ lookup('ansible.builtin.env', 'OPENOBSERVE_PASS') }}"