machine:
  type: controlplane
  kubelet:
    nodeIP:
      validSubnets:
        - 10.20.100.2/32
  install:
    disk: /dev/nvme0n1
    image: factory.talos.dev/metal-installer-secureboot/59762d6112a8f357442daf12c730f242217af688e5ea2c667d8c7013faffead7:v1.12.0
    wipe: true
    grubUseUKICmdline: true
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-control-home-1
---
apiVersion: v1alpha1
kind: DummyLinkConfig
name: dummy0
addresses:
  - address: 10.20.100.2/32
---
apiVersion: v1alpha1
kind: DummyLinkConfig
name: dummy1
addresses:
  - address: 10.20.100.200/32
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
  match: glob("6c:4b:90:21:be:a5", mac(link.permanent_addr))
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth1
selector:
  match: glob("b4:96:91:70:63:3c", mac(link.permanent_addr))
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
addresses:
  - address: 10.20.30.2/24
routes:
  - gateway: 10.20.30.1
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth1
addresses:
  - address: 10.20.40.2/24
