apiVersion: piraeus.io/v1
kind: LinstorNodeConnection
metadata:
  name: linstor-node-connection
  namespace: piraeus-datastore
spec:
  properties:
    - name: DrbdOptions/Net/protocol
      value: A
    - name: DrbdOptions/Net/tls
      value: "yes"