apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.netbox.oss.netboxlabs.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 10m
  chart:
    spec:
      chart: netbox
      version: 5.0.0-beta.15
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
  values:
    existingSecret: netbox-creds
    persistence:
      storageClass: longhorn-crypto-3
    superuser: 
      email: theo@paradisenetworkz.com
      password:
      apiToken:
    service:
      type: LoadBalancer
    redis:
      existingSecret: redis-creds
      existingSecretPasswordKey: password
      resourcesPreset: nano
      global:
        storageClass: longhorn-crypto-3
      replica:
        resourcesPreset: nano
    postgresql:
      existingSecret: postgres-creds
      resourcesPreset: nano
      global:
        storageClass: longhorn-crypto-3
      serviceAccount:
        create: true
        automountServiceAccountToken: false
      rbac:
        create: true