talos_version: 1.10.3
cluster_name: home-cluster
endpoint: https://10.20.0.200:6443
api_server_cert_sans:
  - home-cluster.paradisenetworkz.com

nodes:
  - hostname: talos-control-home-1
    ip_address: 10.20.0.201
    mac_address: 40:b0:34:f5:ac:a6
    install_disk: /dev/nvme0n1
    type: controlplane
    network_interfaces:
      - interface: bond0
        vip: 
          ip: 10.20.0.200
        addresses: 
          - 10.20.0.201/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.20.0.1
        bond:
          deviceSelectors:
            - hardwareAddr: 40:b0:34:f5:ac:a6
          mode: active-backup
  
  - hostname: talos-control-home-2
    ip_address: 10.20.0.202
    mac_address: 6c:4b:90:55:3e:7d
    install_disk: /dev/nvme0n1
    type: controlplane
    network_interfaces:
      - interface: bond0
        vip: 
          ip: 10.20.0.200
        addresses: 
          - 10.20.0.202/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.20.0.1
        bond:
          deviceSelectors:
            - hardwareAddr: 6c:4b:90:55:3e:7d
          mode: active-backup

  - hostname: talos-control-home-3
    ip_address: 10.20.0.203
    mac_address: 6c:4b:90:55:3e:66
    install_disk: /dev/nvme0n1
    type: controlplane
    network_interfaces:
      - interface: bond0
        vip: 
          ip: 10.20.0.200
        addresses: 
          - 10.20.0.203/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.20.0.1
        bond:
          deviceSelectors:
            - hardwareAddr: 6c:4b:90:55:3e:66
          mode: active-backup

official_extensions:
  - siderolabs/drbd
  - siderolabs/i915
  - siderolabs/intel-ucode
  - siderolabs/mei
  - siderolabs/nfsd
  - siderolabs/nvme-cli
  - siderolabs/util-linux-tools

cilium_ipam_operator_cluster_pool_ipv4_pod_cidr_list: 
  - 10.30.0.0/16