---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miroir
  namespace: miroir-system
spec:
  chartRef:
    kind: OCIRepository
    name: miroir
  interval: 1h
  values:
    replicaCount: 3
    drbd:
      verify:
        schedule: 0 8 * * *
