---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./database.yaml
  - ./databaserole.yaml

replacements:
  - source:
      kind: ConfigMap
      name: postgres-app-params
      fieldPath: data.APP
    targets:
      - select:
          kind: Database
          name: APP
        fieldPaths:
          - metadata.name
          - spec.name
          - spec.owner
      - select:
          kind: DatabaseRole
          name: APP
        fieldPaths:
          - metadata.name
          - spec.name
