---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./certificate.yaml
  - ./database.yaml
  - ./databaserole.yaml
  - ./connection-url.yaml

replacements:
  - source:
      kind: ConfigMap
      name: postgres-app-params
      fieldPath: data.APP
    targets:
      - select:
          kind: Certificate
          name: APP-pg-client-cert
        fieldPaths:
          - metadata.name
          - spec.commonName
          - spec.secretName
      - select:
          kind: Database
          name: APP-pg-database
        fieldPaths:
          - metadata.name
          - spec.name
          - spec.owner
      - select:
          kind: DatabaseRole
          name: APP-pg-role
        fieldPaths:
          - metadata.name
          - spec.name
      - select:
          kind: Secret
          name: APP-pg-connection
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: postgres-app-params
      fieldPath: data.PGURL
    targets:
      - select:
          kind: Secret
          name: APP-pg-connection
        fieldPaths:
          - stringData.DATABASE_URL
