apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: "1.13.3"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: false
    enableCertificateOwnerRef: true
    global:
      priorityClassName: system-cluster-critical
    resources:
      requests:
        cpu: 10m
        memory: 32Mi

    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi

    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi

    startupapicheck:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi