- name: Allow dns
  community.general.ufw:
    rule: allow
    port: '53'

- name: Installing bind9
  ansible.builtin.apt:
    name:
      - bind9
    state: present
    update_cache: true

- name: Write the frr config file
  ansible.builtin.template: 
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr

- name: Write the named.conf.options file
  ansible.builtin.template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Write the named.conf.local file
  ansible.builtin.template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Write the forward zone file
  ansible.builtin.template: 
    src: forward-zone.j2
    dest: /var/lib/bind/db.{{ ansible_domain }}
    group: bind
  notify: Restart bind9

- name: Write the reverse zone file
  ansible.builtin.template: 
    src: reverse-zone.j2
    dest: /var/lib/bind/db.{{ ansible_env.AGGREGATE_NETWORK | ansible.utils.ipaddr('revdns') | regex_replace('^[0-9]+\\.+[0-9]+\\.', '') | regex_replace('\.$', '') }}
    group: bind
  notify: Restart bind9

- name: Write the vector config file
  ansible.builtin.template: 
    src: vector.yaml.j2
    dest: /etc/vector/vector.yaml
  notify: Restart vector