- name: Setup packages
  ansible.builtin.include_tasks: packages.yaml

- name: Setup network
  ansible.builtin.include_tasks: network.yaml

- name: Setup logs & metrics
  ansible.builtin.include_tasks: logging.yaml