- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow needed ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: '179'
      proto: tcp
    - port: '9993'
      proto: udp
    - port: '53'
      proto: udp
    - port: '53'
      proto: tcp

- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart frr

- name: Write the frr config file
  ansible.builtin.template: 
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr

- name: Write the named.conf.options file
  ansible.builtin.template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Write the named.conf.local file
  ansible.builtin.template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Write the forward zone file
  ansible.builtin.template: 
    src: forward-zone.j2
    dest: /var/lib/bind/db.{{ ansible_domain }}
    group: bind
  notify: Restart bind9

- name: Write the reverse zone file
  ansible.builtin.template: 
    src: reverse-zone.j2
    dest: /var/lib/bind/db.{{ reverse_zone }}
    group: bind
  notify: Restart bind9

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived