apiVersion: v1
kind: Namespace
metadata:
  name: awx
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-pass
  namespace: awx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: awx-pass
  data:
    - secretKey: password
      remoteRef:
        key: AWX_ADMIN_PASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-secret-key
  namespace: awx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: awx-secret-key
  data:
    - secretKey: secret_key
      remoteRef:
        key: AWX_SECRET_KEY