apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: awx-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://ansible.github.io/awx-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  interval: 10m
  chart:
    spec:
      chart: awx-operator
      version: "2.16.1"
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: flux-system
  values:
    AWX:
      enabled: true
      name: awx
      spec:
        admin_user: admin
        admin_email: theo@paradisenetworkz.com
        admin_password_secret: awx-pass
        secret_key_secret: awx-secret-key
        postgres_storage_class: longhorn-crypto-3
        postgres_data_volume_init: true
        postgres_security_context_settings:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        service_type: LoadBalancer