- name: Install and configure zerotier
  block:
    - name: Add ZeroTier PGP key
      apt_key:
        url: "{{ zerotier_gpg_url }}"
        id: "{{ zerotier_gpg_fingerprint }}"

    - name: Get Zerotier Ubuntu Repo
      uri:
        url: "{{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }}"

    - name: Add ZeroTier APT repository
      apt_repository:
        repo: deb {{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }} {{ zerotier_deb_release_repo }} main
        filename: zerotier

    - name: Installing zerotier
      ansible.builtin.apt:
        name:
          - zerotier-one
        state: present
        update_cache: true

    - name: Allow port 9993 for Zerotier
      community.general.ufw:
        rule: allow
        port: '9993'

    - name: Adding zerotier public key
      ansible.builtin.copy:
        content: "{{ zerotier_public_key }}"
        dest: /var/lib/zerotier-one/identity.public

    - name: Adding zerotier private key
      ansible.builtin.copy:
        content: "{{ zerotier_private_key }}"
        dest: /var/lib/zerotier-one/identity.secret
      notify: Restart zerotier

    - name: Check if the zerotier network conf file exists
      ansible.builtin.stat:
        path: "/var/lib/zerotier-one/networks.d/{{ zerotier_network_id }}.conf"
      register: zerotier_network_file

    - name: Generate zerotier network file
      when: not zerotier_network_file.stat.exists
      ansible.builtin.copy:
        content: ""
        dest: "/var/lib/zerotier-one/networks.d/{{ zerotier_network_id }}.conf"
      notify: Restart zerotier

- name: Install and configure frr
  block: 
    - name: Installing frr
      ansible.builtin.apt:
        name:
          - frr
        state: present
        update_cache: true

    - name: Allow port 179 for BGP
      community.general.ufw:
        rule: allow
        port: '179'

    - name: Write the frr daemon file
      ansible.builtin.copy: 
        src: daemons 
        dest: /etc/frr/daemons

    - name: write the router reflector frr config file
      ansible.builtin.template: 
        src: frr-router-reflector.j2
        dest: /etc/frr/frr.conf
      when: inventory_hostname in groups['route_reflectors']
      notify: Restart frr

    - name: write the control servers frr config file
      ansible.builtin.template: 
        src: frr-k8s.j2
        dest: /etc/frr/frr.conf
      when: inventory_hostname in groups['control_servers']
      notify: Restart frr