---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: percona-pg-operator
  namespace: database-system
spec:
  chart:
    spec:
      chart: pg-operator
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: percona
  interval: 1h
  values:
    replicaCount: 1
    disableTelemetry: true
