---
apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: pg-main
  namespace: database-system
spec:
  postgresVersion: 18
  image: docker.io/perconalab/percona-postgresql-operator:main-ppg18-postgres
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        storageClassName: replica-1-flash
        resources:
          requests:
            storage: 20Gi
  proxy:
    pgBouncer:
      image: docker.io/perconalab/percona-postgresql-operator:main-pgbouncer18
      replicas: 3
  backups:
    pgbackrest:
      image: docker.io/perconalab/percona-postgresql-operator:main-pgbackrest18
      global:
        repo1-path: /pgbackrest/repo1/postgres/pg-main/repo1
        log-path: /pgbackrest/repo1/postgres/pg-main/repo1/log
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteMany
              storageClassName: backup-share
              resources:
                requests:
                  storage: 50Gi
          schedules:
            incremental: "0 2 * * 1-6"
  dataSource:
    pgbackrest:
      stanza: db
      global:
        repo1-path: /pgbackrest/repo1/postgres/pg-main/repo1
        log-path: /pgbackrest/repo1/postgres/pg-main/repo1/log
      repo:
        name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 50Gi
            storageClassName: backup-share
  users:
    - name: authentik
      databases:
        - authentik
