---
- name: Apply K8S Manifests
  become: false
  hosts: localhost
  tasks:
    - name: Apply-Manifests | Generate manifests
      kubernetes.core.helm_template:
        name: "{{ item.name }}"
        chart_ref: "{{ item.chart_ref }}"
        chart_version: "{{ item.chart_version }}"
        release_namespace: "{{ item.release_namespace }}"
        values: "{{ item['values'] }}"
        include_crds: true
      register: manifests
      loop:
        - name: "{{ lookup('file', '../kubernetes/kube-system/cilium/app/ocirepository.yaml') | from_yaml | json_query('metadata.name') }}"
          chart_ref: "{{ lookup('file', '../kubernetes/kube-system/cilium/app/ocirepository.yaml') | from_yaml | json_query('spec.url') }}"
          chart_version: "{{ lookup('file', '../kubernetes/kube-system/cilium/app/ocirepository.yaml') | from_yaml | json_query('spec.ref.tag') }}"
          release_namespace: "{{ lookup('file', '../kubernetes/kube-system/cilium/app/kustomization.yaml') | from_yaml | json_query('namespace') }}"
          values: "{{ lookup('file', '../kubernetes/kube-system/cilium/app/helmrelease.yaml') | from_yaml | json_query('spec.values') }}"

        - name: "{{ lookup('file', '../kubernetes/spegel/app/ocirepository.yaml') | from_yaml | json_query('metadata.name') }}"
          chart_ref: "{{ lookup('file', '../kubernetes/spegel/app/ocirepository.yaml') | from_yaml | json_query('spec.url') }}"
          chart_version: "{{ lookup('file', '../kubernetes/spegel/app/ocirepository.yaml') | from_yaml | json_query('spec.ref.tag') }}"
          release_namespace: "{{ lookup('file', '../kubernetes/spegel/app/kustomization.yaml') | from_yaml | json_query('namespace') }}"
          values: "{{ lookup('file', '../kubernetes/spegel/app/helmrelease.yaml') | from_yaml | json_query('spec.values') }}"

        - name: "{{ lookup('file', '../kubernetes/cert-manager/app/ocirepository.yaml') | from_yaml | json_query('metadata.name') }}"
          chart_ref: "{{ lookup('file', '../kubernetes/cert-manager/app/ocirepository.yaml') | from_yaml | json_query('spec.url') }}"
          chart_version: "{{ lookup('file', '../kubernetes/cert-manager/app/ocirepository.yaml') | from_yaml | json_query('spec.ref.tag') }}"
          release_namespace: "{{ lookup('file', '../kubernetes/cert-manager/app/kustomization.yaml') | from_yaml | json_query('namespace') }}"
          values: "{{ lookup('file', '../kubernetes/cert-manager/app/helmrelease.yaml') | from_yaml | json_query('spec.values') }}"

        - name: "{{ lookup('file', '../kubernetes/piraeus-datastore/app/ocirepository.yaml') | from_yaml | json_query('metadata.name') }}"
          chart_ref: "{{ lookup('file', '../kubernetes/piraeus-datastore/app/ocirepository.yaml') | from_yaml | json_query('spec.url') }}"
          chart_version: "{{ lookup('file', '../kubernetes/piraeus-datastore/app/ocirepository.yaml') | from_yaml | json_query('spec.ref.tag') }}"
          release_namespace: "{{ lookup('file', '../kubernetes/piraeus-datastore/app/kustomization.yaml') | from_yaml | json_query('namespace') }}"
          values: "{{ lookup('file', '../kubernetes/piraeus-datastore/app/helmrelease.yaml') | from_yaml | json_query('spec.values') }}"

        - name: "{{ lookup('file', '../kubernetes/flux-system/app/ocirepository.yaml') | from_yaml | json_query('metadata.name') }}"
          chart_ref: "{{ lookup('file', '../kubernetes/flux-system/app/ocirepository.yaml') | from_yaml | json_query('spec.url') }}"
          chart_version: "{{ lookup('file', '../kubernetes/flux-system/app/ocirepository.yaml') | from_yaml | json_query('spec.ref.tag') }}"
          release_namespace: "{{ lookup('file', '../kubernetes/flux-system/app/kustomization.yaml') | from_yaml | json_query('namespace') }}"
          values: "{{ lookup('file', '../kubernetes/flux-system/app/helmrelease.yaml') | from_yaml | json_query('spec.values') }}"

    - name: Apply-Manifests | Apply manifests
      kubernetes.core.k8s:
        state: present
        definition: "{{ item }}"
        wait: true
        continue_on_error: true
      loop:
        - "{{ manifests.results.0.stdout | from_yaml_all }}"
        - "{{ lookup('file', '../kubernetes/spegel/app/namespace.yaml') | from_yaml }}"
        - "{{ manifests.results.1.stdout | from_yaml_all }}"
        - "{{ lookup('file', '../kubernetes/cert-manager/app/namespace.yaml') | from_yaml }}"
        - "{{ manifests.results.2.stdout | from_yaml_all }}"
        - "{{ lookup('file', '../kubernetes/piraeus-datastore/app/namespace.yaml') | from_yaml }}"
        - "{{ manifests.results.3.stdout | from_yaml_all }}"
        - "{{ lookup('file', '../kubernetes/flux-system/app/namespace.yaml') | from_yaml }}"
        - "{{ manifests.results.4.stdout | from_yaml_all }}"
        - apiVersion: fluxcd.controlplane.io/v1
          kind: FluxInstance
          metadata:
            name: flux
            namespace: flux-system
          spec:
            distribution:
              version: 2.x
              registry: ghcr.io/fluxcd
            components:
              - source-controller
              - kustomize-controller
              - helm-controller
              - notification-controller
            cluster:
              type: kubernetes
              multitenant: false
              networkPolicy: true
              domain: cluster.local
            sync:
              kind: GitRepository
              url: https://github.com/TheoBassaw/home-prod.git
              ref: refs/heads/main
              path: kubernetes
              interval: 1h
