---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: storage-system
stringData:
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: openbao-oci-config
  namespace: security-system
stringData:
  config: |
    [DEFAULT]
    user=${OCI_USER}
    fingerprint=${OCI_FINGERPRINT}
    key_file=/home/openbao/.oci/key.pem
    tenancy=${OCI_TENANCY}
    region=${OCI_REGION}
  key.pem: ${OCI_PRIVATE_KEY}
