[secrets]
OCI_FINGERPRINT = { provider = "pass", value = "kubernetes/OCI_FINGERPRINT" }
OCI_PRIVATE_KEY = { provider = "pass", value = "kubernetes/OCI_PRIVATE_KEY" }
OCI_PUBLIC_KEY  = { provider = "pass", value = "kubernetes/OCI_PUBLIC_KEY" }
S3_ACCESS_KEY   = { provider = "pass", value = "kubernetes/S3_ACCESS_KEY" }
S3_SECRET_KEY   = { provider = "pass", value = "kubernetes/S3_SECRET_KEY" }
