---
- name: Talos Configuration | Make sure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/.talos/{{ cluster_name }}"
    - "~/.kube"

- name: Talos Configuration | Upload schematic to image factory
  ansible.builtin.uri:
    url: https://factory.talos.dev/schematics
    method: POST
    body: "{{ schematic | to_yaml }}"
    body_format: raw
    status_code: 201
  register: schematic

- name: Talos Configuration | Generate secret bundle
  ansible.builtin.command: "talosctl gen secrets --output-file ~/.talos/{{ cluster_name }}/secrets.yaml"
  args:
    creates: "~/.talos/{{ cluster_name }}/secrets.yaml"

- name: Talos Configuration | Generate machine configs
  ansible.builtin.command: |
    talosctl gen config "{{ cluster_name }}" "{{ endpoint }}" \
    --with-secrets "~/.talos/{{ cluster_name }}/secrets.yaml" \
    --output-types "{% if item.machine_config.machine.type == 'controlplane' %}controlplane{% else %}worker{% endif %}" \
    --output "~/.talos/{{ cluster_name }}/{{ item.machine_config.machine.network.hostname }}.yaml" \
    --config-patch "{{ all_config_patch }}"
    --config-patch "{{ item.machine_config }}"
  args:
    creates: "~/.talos/{{ cluster_name }}/{{ item.machine_config.machine.network.hostname }}.yaml"
  loop: "{{ nodes }}"

- name: Talos Configuration | Generate talconfig
  ansible.builtin.command: |
    talosctl gen config "{{ cluster_name }}" "{{ endpoint }}" \
    --with-secrets "~/.talos/{{ cluster_name }}/secrets.yaml" \
    --output-types talosconfig --output "~/.talos/{{ cluster_name }}/{{ cluster_name }}"
  args:
    creates: "~/.talos/{{ cluster_name }}/{{ cluster_name }}"

- name: Talos Bootstrap | Bootstrap controlplane
  ansible.builtin.command: |
    talosctl bootstrap --nodes "{{ ansible_host }}" \
    --endpoints "{{ ansible_host }}" \
    --talosconfig "~/.talos/{{ cluster_name }}"
  register: result
  changed_when: false
  failed_when: "'error executing bootstrap: rpc error: code = Unavailable desc = connection error' in result.stderr"
  retries: 30
  delay: 10

- name: Talos Bootstrap | Generate kubeconfig
  ansible.builtin.command: |
    talosctl kubeconfig --nodes "{{ ansible_host }}" \
    --endpoints "{{ ansible_host }}" \
    --talosconfig "~/.talos/{{ cluster_name }}"
  changed_when: false

- name: Talos Bootstrap | Add cilium helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Talos Bootstrap | Apply cilium helm chart
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.17.4"
    release_namespace: kube-system
    update_repo_cache: true
    context: "admin@{{ cluster_name }}"
    kubeconfig: "~/.kube/config"
    wait: true
    values_files:
      - "{{ playbook_dir }}/../kubernetes/clusters/{{ cluster_name }}/kube-system/cilium/helm-values.yaml"
  retries: 30
  delay: 10

- name: Talos Bootstrap | Apply flux-operator helm chart
  kubernetes.core.helm:
    name: flux-operator
    chart_ref: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    chart_version: "0.22.0"
    release_namespace: flux-system
    create_namespace: true
    update_repo_cache: true
    context: "admin@{{ cluster_name }}"
    kubeconfig: "~/.kube/config"
    wait: true

- name: Talos Bootstrap | Start flux cluster sync
  kubernetes.core.k8s:
    src: "{{ playbook_dir }}/../kubernetes/clusters/{{ cluster_name }}/flux-system/flux-instance.yaml"
    wait: true
