global:
  enabled: false
server:
  enabled: true
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: http-issuer
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: ${vault_url}
        paths:
          - /
    tls:
      - secretName: vault-tls
        hosts:
          - ${vault_url}
  extraEnvironmentVars:
    VAULT_OCIKMS_SEAL_KEY_ID: ${seal_key_id}
    VAULT_OCIKMS_CRYPTO_ENDPOINT: ${crypto_endpoint}
    VAULT_OCIKMS_MANAGEMENT_ENDPOINT: ${management_endpoint}
    VAULT_SEAL_TYPE: "ocikms"
  dataStorage:
    storageClass: longhorn
    size: 5Gi
  auditStorage:
    enabled: true
    storageClass: longhorn
    size: 5Gi
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = "true"
      }

      storage "file" {
        path = "/vault/data"
      }
