- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Installing frr
  ansible.builtin.apt:
    name:
      - frr
    state: present
    update_cache: true

- name: Allow bgp
  community.general.ufw:
    rule: allow
    port: '179'

- name: Allow Zerotier Devices to access
  community.general.ufw:
    rule: allow
    route: true
    if_in: zt1
    if_out: zt0
    
- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart frr

- name: write the host frr config file
  ansible.builtin.template: 
    src: ingress.conf.j2
    dest: /etc/frr/frr.conf
  notify: Restart frr

- name: Setup Nginx
  include_role: 
    name: nginxinc.nginx