- name: Allow port 9993 for zerotier
  community.general.ufw:
    rule: allow
    port: '9993'

- name: Add zeroTier pgp key
  apt_key:
    url: https://download.zerotier.com/contact@zerotier.com.gpg
    id: 74A5E9C458E1A431F1DA57A71657198823E52A61

- name: Add zeroTier apt repository
  apt_repository:
    repo: deb http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main
    filename: zerotier

- name: Installing zerotier
  ansible.builtin.apt:
    name:
      - zerotier-one
    state: present
    update_cache: true
  notify: Restart zerotier