- name: Installing libvirt & qemu
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
    state: present
    update_cache: true

- name: Add ubuntu to libvirt group
  ansible.builtin.user:
    name: ubuntu
    groups: libvirt
    append: yes

- name: Add ansible to libvirt group
  ansible.builtin.user:
    name: ansible
    groups: libvirt
    append: yes

- name: Remove libvirt default network
  ansible.builtin.file:
    path: /etc/libvirt/qemu/networks/autostart/default.xml
    state: absent
  notify: Restart libvirtd