apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
# SelfSigned issuers
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Root ca
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor
  duration: 87600h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
  - cert sign
  - crl sign
---
# The Root CA issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-intermediate-issuer
spec:
  ca:
    secretName: linkerd-trust-anchor
---
# Intermediate ca
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  isCA: true
  commonName: identity.linkerd.cluster.local
  secretName: linkerd-identity-issuer
  duration: 48h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - identity.linkerd.cluster.local
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
# Trust bundle
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
  - secret:
      name: "linkerd-trust-anchor"
      key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"