apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  annotations:
    linkerd.io/inject: enabled