---
machine:
  install:
    disk: /dev/disk/by-id/nvme-eui.ace42e8170470927
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
  match: mac(link.permanent_addr) == "6c:4b:90:55:3e:66"
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
addresses:
  - address: 10.20.0.15/24
routes:
  - gateway: 10.20.0.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.20.0.200
link: eth0
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-control-3.home.paradisenetworkz.com
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-data-1
provisioning:
  diskSelector:
    match: disk.wwid == "nvme.1987-3232303431393531323030303331-5043496520535344-00000001"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
