---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: kube-system
spec:
  interval: 10m
  url: https://intel.github.io/helm-charts/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: '0.34.0'
      sourceRef:
        kind: HelmRepository
        name: intel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: '0.34.0'
      sourceRef:
        kind: HelmRepository
        name: intel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    name: gpudeviceplugin
