apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: global-secrets
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:BNSB2h/gHPBvGDwXP4AzTsn1G+7swBN2IiDUydHqGsQPYBgxWeiOqPIvp9SPDcZszqqbgNY=,iv:ToJvUCI9xzKLjsmI3kqD0z+T6ijNy6NJ4OlISkfNfFI=,tag:O1j0jUMnT9XqifWZ0lxlQw==,type:str]
sops:
  age:
    - recipient: age1yvpeenghcvzvun90nzrvxf3jekkev0tdn3rnsd5u0cnphulkavfq2v93qt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT0x5MmpiMEVZS1hqb0c4
        YnBwQys0eVZTSStXOTJ3NlYydDROaldXTDJNCjR0a2ZkbVpjbWgzdTljZkpqd1Bu
        Sk9RbXRzZ0VkRStod25WbnlRVU4wcDAKLS0tIGpseGkvaFBlVTVYNTJ5dWl4ay9S
        TXNieUF3a1E4OFlKdnJrSGhKc3NURGsKDRVIEgWU6QlIccvZHZP2T1Vc5YlJL4Mr
        heznjvI0k+UqJo9YqXHdM9EGEuwB0R3fLFPo9/VYYW3mu18Q0BqzTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T05:38:49Z"
  mac: ENC[AES256_GCM,data:Ug0G93bKRdzwOdHNWGT+FPyYtwTvD5Vxr/1wFYonYT4raJsKJCksOzJoaWRbKuDLli7aATtA3l+lQlUHaOExHmgZyC5uS/8zbgjnfLUAFo6YoI8PfWqVq/ahk1wRuoeRK6EFbW2g7YyvFzTj5grK2hE9WWipKKeAWPevZHb9FHI=,iv:7IMaatK7AJuAyIMiOx282JktLuZeoL5l5By+3D5NRsY=,tag:sZbEtyBpQIYMwNtPu9UbOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
