---
machine:
  install:
    wipe: true
    grubUseUKICmdline: true
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
  files:
    - path: /etc/cri/conf.d/20-customization.part
      op: create
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      - name: dm-thin-pool
cluster:
  network:
    cni:
      name: none
    podSubnets:
      - 10.30.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  proxy:
    disabled: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        checkSecurebootStatusOnEnroll: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        checkSecurebootStatusOnEnroll: true
      lockToState: true
