---
- name: Gather ansible controller facts
  hosts: localhost

- name: Create talos cluster
  become: false
  hosts: all
  gather_facts: false
  vars:
    ansible_controller_ip: "{{ hostvars['localhost'].ansible_default_ipv4.address }}"
    ansible_controller_network: "{{ hostvars['localhost'].ansible_default_ipv4.network }}"
    ansible_controller_netmask: "{{ hostvars['localhost'].ansible_default_ipv4.netmask }}"
  roles:
    - talos-metal
