---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1h
  path: kubernetes/apps/kube-system/metrics-server
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: spegel
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m