apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
  namespace: k0smotron
spec:
  version: v1.31.1-k0s.0
  etcd:
    persistence:
      storageClass: longhorn-2
      size: 8Gi
  persistence:
    type: pvc
    persistentVolumeClaim:
      spec:
        storageClassName: longhorn-2
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  service:
    type: ClusterIP
    apiPort: 6443
    konnectivityPort: 8132
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: custom