---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-crds
  namespace: network-system
spec:
  interval: 15m
  ref:
    tag: v1.7.1
  url: oci://registry-1.docker.io/envoyproxy/gateway-crds-helm
