apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openobserve
  namespace: fluent-bit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: openobserve-creds
  data:
    - secretKey: OPENOBSERVE_USER
      remoteRef:
        key: OPENOBSERVE_USER
    - secretKey: OPENOBSERVE_PASS
      remoteRef:
        key: OPENOBSERVE_PASS