---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: piraeus-datastore
spec:
  interval: 1h
  path: ./kubernetes/piraeus-datastore/helm
  prune: true
  retryInterval: 2m
  wait: true
  dependsOn:
    - name: spegel
      namespace: kube-system
    - name: cert-manager
      namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m