- name: Add gpg keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - url: https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
      dest: /etc/apt/keyrings/timber-vector-archive-keyring.asc
    - url: https://download.zerotier.com/contact@zerotier.com.gpg
      dest: /etc/apt/keyrings/zerotier.com.asc

- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - deb [signed-by=/etc/apt/keyrings/timber-vector-archive-keyring.asc] https://repositories.timber.io/public/vector/deb/ubuntu {{ ansible_facts['distribution_release'] }} main
    - deb [signed-by=/etc/apt/keyrings/zerotier.com.asc] http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main

- name: Installing needed applications
  ansible.builtin.apt:
    name:
      - zerotier-one
      - frr
      - bind9
      - vector
    state: present
    update_cache: true
  notify: Restart zerotier

- name: Gather new facts
  ansible.builtin.setup:

- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow needed ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: '179'
      proto: tcp
    - port: '9993'
      proto: udp
    - port: '53'
      proto: udp
    - port: '53'
      proto: tcp

- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart frr

- name: Write config files
  ansible.builtin.template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: frr.conf.j2
      dest: /etc/frr/frr.conf
    - src: named.conf.options.j2
      dest: /etc/bind/named.conf.options
    - src: named.conf.local.j2
      dest: /etc/bind/named.conf.local
    - src: vector.yaml.j2
      dest: /etc/vector/vector.yaml
  notify: 
    - Restart frr
    - Restart bind9
    - Restart vector

- name: Write zone files
  ansible.builtin.template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ item.group }}"
  loop:
    - src: forward-zone.j2
      dest: /var/lib/bind/db.{{ ansible_domain }}
      group: bind
    - src: reverse-zone.j2
      dest: /var/lib/bind/db.{{ reverse_zone }}
      group: bind
  notify: Restart bind9