- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow bgp & zerotier
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
   - '179'
   - '9993'

- name: Add zerotier pgp key
  apt_key:
    url: https://download.zerotier.com/contact@zerotier.com.gpg
    id: 74A5E9C458E1A431F1DA57A71657198823E52A61

- name: Add zerotier apt repository
  apt_repository:
    repo: deb http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main
    filename: zerotier

- name: Add vector gpg key
  ansible.builtin.get_url:
    url: https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
    dest: /usr/share/keyrings/timber-vector-archive-keyring.asc
    mode: '0644'

- name: Add vector apt repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/timber-vector-archive-keyring.asc] https://repositories.timber.io/public/vector/deb/ubuntu {{ ansible_facts['distribution_release'] }} main

- name: Installing needed applications
  ansible.builtin.apt:
    name:
      - zerotier-one
      - frr
      - vector
    state: present
    update_cache: true
  notify: Restart zerotier

- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart frr