apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kamaji-db
  namespace: kamaji-system
spec:
  instances: 2
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
      - hostssl kamaji all all cert
  bootstrap:
    initdb:
      database: kamaji
      owner: kamaji
  storage:
    size: 10Gi
    storageClass: local-path