apiVersion: v1
data:
  daemons: |
    zebra=yes
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    staticd=no
    pbrd=no
    bfdd=yes
    fabricd=no
    vtysh_enable=yes
    zebra_options=" -s 90000000 --daemon -A 127.0.0.1"
    bgpd_options="   --daemon -A 127.0.0.1"
    ospfd_options="  --daemon -A 127.0.0.1"
    ospf6d_options=" --daemon -A ::1"
    ripd_options="   --daemon -A 127.0.0.1"
    ripngd_options=" --daemon -A ::1"
    isisd_options="  --daemon -A 127.0.0.1"
    pimd_options="  --daemon -A 127.0.0.1"
    ldpd_options="  --daemon -A 127.0.0.1"
    nhrpd_options="  --daemon -A 127.0.0.1"
    eigrpd_options="  --daemon -A 127.0.0.1"
    babeld_options="  --daemon -A 127.0.0.1"
    sharpd_options="  --daemon -A 127.0.0.1"
    staticd_options="  --daemon -A 127.0.0.1"
    pbrd_options="  --daemon -A 127.0.0.1"
    bfdd_options="  --daemon -A 127.0.0.1"
    fabricd_options="  --daemon -A 127.0.0.1"
  frr.conf: |
    frr defaults datacenter
    log syslog informational
    service integrated-vtysh-config
    !
    router bgp 212364 view RR
    bgp router-id ${router_ip}
    bgp log-neighbor-changes
    bgp graceful-restart
    neighbor mesh peer-group
    neighbor mesh remote-as 212364
    bgp listen range 10.30.16.0/24 peer-group mesh
    !
    address-family ipv4 unicast
      neighbor mesh activate
      neighbor mesh route-reflector-client
      neighbor mesh soft-reconfiguration inbound
    exit-address-family
    !
    line vty
    !
kind: ConfigMap
metadata:
  name: frr