- name: Add gpg keys
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - url: https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
      dest: /etc/apt/keyrings/timber-vector-archive-keyring.asc
    - url: https://download.zerotier.com/contact@zerotier.com.gpg
      dest: /etc/apt/keyrings/zerotier.com.asc

- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - deb [signed-by=/etc/apt/keyrings/timber-vector-archive-keyring.asc] https://repositories.timber.io/public/vector/deb/ubuntu {{ ansible_facts['distribution_release'] }} main
    - deb [signed-by=/etc/apt/keyrings/zerotier.com.asc] http://download.zerotier.com/debian/{{ ansible_facts['distribution_release'] }} {{ ansible_facts['distribution_release'] }} main

- name: Installing needed applications
  ansible.builtin.apt:
    name:
      - zerotier-one
      - frr
      - keepalived
      - conntrack
      - conntrackd
      - vector
    state: present
    update_cache: true
  notify: Restart zerotier

- name: Gather new facts
  ansible.builtin.setup:

- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow needed ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - port: '179'
      proto: tcp
    - port: '9993'
      proto: udp
    - port: '3780'
      proto: udp

- name: Allow devices to overlay
  community.general.ufw:
    rule: allow
    route: true
    src: "{{ (ansible_zt1.ipv4.address + '/' + ansible_zt1.ipv4.netmask) | ansible.utils.ipaddr('network/prefix') }}"
    dest: "{{ aggregate_network }}"

- name: Allow keepalived multicast
  community.general.ufw:
    rule: allow
    to: '224.0.0.18'

- name: Write the frr daemon file
  ansible.builtin.copy: 
    src: daemons 
    dest: /etc/frr/daemons
  notify: Restart keepalived

- name: Write config files
  ansible.builtin.template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: frr.conf.j2
      dest: /etc/frr/frr.conf
    - src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
    - src: conntrackd.conf.j2
      dest: /etc/conntrackd/conntrackd.conf
    - src: vector.yaml.j2
      dest: /etc/vector/vector.yaml
  notify: 
    - Restart keepalived
    - Restart conntrackd
    - Restart vector