- become: true
  hosts: all
  name: Install Zerotier and frr
  roles:
    - role: zerotier-frr

- become: true
  hosts: control_servers
  name: Setup k8s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - role: k8s