rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d

engine:
  kind: modern_ebpf
  modern_ebpf:
    cpus_for_each_buffer: 2
    buf_size_preset: 4
    drop_failed_exit: false

outputs_queue:
  capacity: 0

syslog_output:
  enabled: true

syscall_event_timeouts:
  max_consecutives: 1000

syscall_event_drops:
  threshold: .1
  actions:
    - log
    - alert
  rate: .03333
  max_burst: 1
  simulate_drops: false


watch_config_files: true
buffered_outputs: true
rule_matching: first
priority: debug
log_syslog: true
log_level: info
output_timeout: 2000
syscall_buf_size_preset: 4