- name: Download rke2 binary
  ansible.builtin.get_url:
    url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64
    checksum: sha256:https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/rke2
    mode: 0755

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/rancher/rke2

- name: Copy k3s config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - src: config.yaml.j2
      dest: /etc/rancher/rke2/config.yaml
    - src: rke2-server.service.j2
      dest: /etc/systemd/system/rke2-server.service
    - src: cilium-helm.yaml.j2
      dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml

- name: Enable rke2 service
  ansible.builtin.systemd:
    name: rke2-server
    enabled: true
    state: started
  register: rke2_service
  until: rke2_service is succeeded
  retries: 5

- name: Get Kubernetes config file
  run_once: true
  ansible.builtin.slurp:
    src: /etc/rancher/rke2/rke2.yaml
  register: kubeconfig_base64

- name: Write Kubernetes config file with the correct cluster address
  ansible.builtin.copy:
    content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', ansible_env.VIP) }}"
    dest: "${HOME}/.kube/k8s-home.yaml"
    mode: 0600
  delegate_to: localhost
  run_once: true
  become: false