---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 10m
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  ref:
    tag: 0.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: spegel
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
