---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1h
  path: kubernetes/apps/spegel
  prune: true
  retryInterval: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: spegel
      namespace: spegel
  timeout: 10m
