---
machine:
  install:
    disk: /dev/disk/by-id/nvme-eui.ace42e8170470a42
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
  match: mac(link.permanent_addr) == "98:6e:e8:23:bc:43"
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
addresses:
  - address: 10.20.0.42/24
routes:
  - gateway: 10.20.0.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.20.0.201
link: eth0
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: talos-nas-control-1.home.paradisenetworkz.com
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-rust-1
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5000c500b217a70b"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-rust-2
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5000c500b217a897"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: piraeus-rust-3
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5000c5009e16594b"
  grow: true
  minSize: 500GB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
